index:
  Index:
    Index:
      index:
        param1: 0
        param2: 1
      decuong:
      dsdecuong: 
      indecuong:
phanbocanbo:
  Phongban:
    Index:
      save:
        param1: 0
        param2: 0
phongbankhoa:
  Phongban:
    Hoso:
      tientrinh:
tkb:
  Thoikhoabieu:
    Phanbo:
      index:
        dothoc: 0
        makhoa: 0
      indexbomon:
        dothoc: 0
        makhoa: 0
      save:
        dothoc: 0
        lop: 0
        mamh: 0
        loai: 0
      savebomon:
        dothoc: 0
        lop: 0
        mamh: 0
        loai: 0
      preview:
      previewbommon:
      list:
      listbomon:
      test:
        param1: 0
      test2:
migration:
  Migration:
    Index:
      index:
admin:
  System:
    System:
      listuser:
      change:
    Mail:
      tbtkb:
      tkbgetemail:
      tkbsendmaildone:
        id: 0
      template:
      change:
cronjob:
  Cronjob:
    Index:
      index:
        name:
khcn:
  Khcn:
    Phanbien:
      index:
      list:
      save:
      ajaxdialog:
      yes:
      no:
      printpdfbm01:
      printpdfbm06:
login:
  Login:
    Index:
      index:
      register:
      logout:
      login:
    Cas:
      index:
      destroy: