<?php
	ini_set('display_errors', '1');
	
	$to = "lhttung@hcmut.edu.vn";
	$from = "Admin <taint@hcmut.edu.vn>";
	$subject = "Test Attachment Email";

	$separator = md5(time());

	// carriage return type (we use a PHP end of line constant)
	$eol = PHP_EOL;

	// attachment name
	$filename = "logs.zip";

	//$pdfdoc is PDF generated by FPDF
	$attachment = chunk_split(base64_encode(file_get_contents($filename)));
	
	// main header
	$headers  = "From: ".$from.$eol;
	$headers .= "MIME-Version: 1.0".$eol; 
	$headers .= "Content-Type: multipart/mixed; boundary=\"".$separator."\"";

	// no more headers after this, we start the body! //

	$body = "--".$separator.$eol;
	$body .= "Content-Transfer-Encoding: 7bit".$eol.$eol;
	$body .= "This is a MIME encoded message.".$eol;

	// message
	$body .= "--".$separator.$eol;
	$body .= "Content-Type: text/html; charset=\"utf-8\"".$eol;
	$body .= "Content-Transfer-Encoding: 8bit".$eol.$eol;
	$body .= "<b>Thôi rồi lợm ơi!</b>".$eol;

	// attachment
	$body .= "--".$separator.$eol;
	$body .= "Content-Type: application/octet-stream; name=\"".$filename."\"".$eol; 
	$body .= "Content-Transfer-Encoding: base64".$eol;
	$body .= "Content-Disposition: attachment".$eol.$eol;
	$body .= $attachment.$eol;
	$body .= "--".$separator."--";

	// send message
	if (mail($to, '=?UTF-8?B?'.base64_encode($subject).'?=', $body, $headers)) {
		echo "mail send ... to $to OK";
	} else {
		echo "mail send ... ERROR";
	}
?>
